### PR TITLE
Pull request temp

### PR DESCRIPTION
**Pull request by sarafurd**

### CODE REVIEW

**Comment by Alexandra-Haynes** [comment]
Sara, this is my last comment on this PR. If you want your changes to be merged, go through all our conversation and read everything again + **preview your md file before submitting it**! This conversation will be closed in 24h, please make your final (and correct) commit within this time. We do need this template setup in place for Hacktoberfest contributors asap.

**Comment by sarafurd** [comment]
Sorry I'm really confused

**Comment by sarafurd** [comment]
- Fixed the html comments 
- Got rid of the extra white space

image

**Review by Alexandra-Haynes — CHANGES_REQUESTED** [review]
Please copy & paste this:
```
<!-- 
NOTE: The comments enclosed in these brackets are guides and will not be visible in your pull request description. Please make sure to fill out all the sections as necessary and remove the comments before submitting your PR.
Please provide a brief description of the changes made in this PR for the "Code with Aloha Website".
-->

# Summary

## Changes
<!-- Please mark the line that applies with an x: [x] -->
- [ ] **Updated Section:** <!--(please specify which section) -->
- [ ] **Added new feature:** <!-- (please describe) -->
- [ ] **Fixed a bug:** <!-- (please describe) -->
- [ ] **Updated documentation**

## Checklist
<!-- Please mark the line that applies with an x: [X] -->
- [ ] I have tested my changes thorougly
- [ ] I have linked the related issue (Ex: fixes #12, closes #123 in the PR description)

## Related Issue

<!--Please link to any related issue or provide context for the changes. -->

## Screenshots

<!-- If your changes affect the UI or layout, please attach before-and-after screenshots. -->

## How I Tested

<!-- Please describe how you tested the changes (e.g., locally, on the live site, etc.). -->

## Notes

<!-- Any additional information or context about the changes.

Thank you for contributing to the Code with Aloha Website! We appreciate your effort and dedication to improving the community through technology.

Commit and push the changes -->
```

This way **all** instructions are commented out and **all** subtitles (except for Summary) are of second order (##)

**Review by Alexandra-Haynes — APPROVED** [review]

**Pull request merged**
