### PR TITLE
Setup linter

### PR DESCRIPTION
**Pull request by MichaelTamaki**
Setup linter

When I ran `npm run lint`, it showed me this output:

```
@MichaelTamaki ➜ /workspaces/CWAWebsite (main) $ npm run lint

> code-with-aloha@0.1.0 lint
> next lint

? How would you like to configure ESLint? https://nextjs.org/docs/basic-features/eslint
❯  Strict (recommended)
   Base
   Cancel
```

So I selected `Strict`, and it outputted the files you see in the first commit. There was only one ESLint error for not escaping an `'`.

The second commit is to set up a Github Action that checks for errors during `npm run lint` or `npm run build`. To ensure consistency across Github Actions and local development, I added a `.nvmrc` file so they all use the same NodeJS version. The commit also adds some instructions to the readme.

### CODE REVIEW

**Comment by MichaelTamaki** [comment]
Github Actions doesn't look like it was initialized here -- could a repo maintainer/owner check the settings to see if you need to allow outside collaborators to start workflows?

**Review by Alexandra-Haynes — APPROVED** [review]
Michael, I made some modifications to the readme, to resolve the conflicts and give it a easy-to-follow structure. Thank you for your contributions. We'll be waiting for another review and then we can merge it 🔥

**Comment by MichaelTamaki** [comment]
Looks like the github action ran on my fork... I assume it will run here once it's merged too https://github.com/MichaelTamaki/CWAWebsite/actions/runs/6177514330/job/16768804218

**Review by avenmia — APPROVED** [review]
lgtm! :shipit:

**Pull request merged**
